idf_component_register(
    SRCS
        "main.c"
        "audio_pipeline.c"
        "codec_lc3.c"
        "mesh_mac.c"
        "mesh_proto.c"
        "mixer.c"
        "mixer_jb.c"
        "bt_classic.c"
        "session_fsm.c"
        "ui.c"
        "nvs_cfg.c"
        "coex.c"
    INCLUDE_DIRS "."
    REQUIRES
        nvs_flash
        esp_wifi
        esp_coex
        bt
        driver
        esp_driver_gpio
        esp_driver_i2c
        esp_driver_i2s
        esp_event
        esp_timer
        liblc3
        esp_codec_dev
        webrtc_ns
)
